name: Sheet to Json Workflow

on:
  schedule:
    # every 10 minutes the job will run
    - cron: "*/10 * * * *"
  push:
    branches:
      - master

jobs:
  update-json-data:
    runs-on: ubuntu-latest
    timeout-minutes: 9

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: push
        run: |
          bash ./pushthejson
          echo "the job completed"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          BOT_TOKEN: ${{ secrets.bot_token }}
          SHEET_ID_v1: ${{ secrets.SHEET_ID_v1 }}
          SHEET_ID_v2: ${{ secrets.SHEET_ID_v2 }}
          RESOURCES_SHEET_ID: ${{ secrets.RESOURCES_SHEET_ID }}
          STUCK_BOT: ${{ secrets.STUCK_BOT }}
      - name: show job status
        if: always()
        run: |
          git checkout master
          node lib/notify_tg.js $STUCK_BOT $status
        env:
          status: ${{job.status}}
          STUCK_BOT: ${{ secrets.STUCK_BOT }}
#trigger the action
#trigger the action by remove this line
